# Generated by Django 3.0.5 on 2020-04-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0044_auto_20200421_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupernetVPN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supernet', models.CharField(help_text='Supernet block for devices.', max_length=20, unique=True)),
                ('subnet', models.CharField(help_text='Subnet for back to back.', max_length=20, unique=True)),
                ('vpn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_netjsonconfig.Vpn')),
            ],
            options={
                'verbose_name': 'Supernet VPN',
                'verbose_name_plural': 'Supernets VPN',
                'abstract': False,
                'unique_together': {('supernet', 'vpn')},
            },
        ),
    ]
