# Generated by Django 3.0.5 on 2020-04-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0045_supernetvpn'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpamSubnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_netjsonconfig.IpamSubnet')),
            ],
            options={
                'verbose_name': 'IPAM subnet',
                'verbose_name_plural': 'IPAM subnets',
                'abstract': False,
            },
        ),
    ]
