# Generated by Django 3.0.5 on 2020-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0047_auto_20200423_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supernetvpn',
            name='subnet',
            field=models.CharField(help_text='Subnet for back to back.', max_length=20),
        ),
    ]
